name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: 'v1.25.2'  # Set the version of Minikube (you can adjust this)

    - name: Verify Minikube Cluster is Running
      run: |
        minikube status

    - name: Try Kubernetes Cluster (Get Pods)
      run: |
        kubectl get pods -A

    - name: Build Docker Image for Node.js App
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        echo "Verifying Docker Images:"
        docker images

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s-node-app.yaml

    - name: Verify Deployment Status
      run: |
        kubectl get deployments -A
        kubectl get pods -A

    - name: Check Service and Pod Logs
      run: |
        # Check if the nodejs-app pod is running
        kubectl get pods -l app=nodejs-app
        kubectl logs -l app=nodejs-app

    - name: Get Minikube Logs for Troubleshooting
      run: |
        minikube logs

    - name: Wait for Pods to be Ready
      run: |
        kubectl wait --for=condition=ready pod --all --timeout=60s

    - name: Check Service Status
      run: |
        kubectl get svc -A
        kubectl describe svc nodejs-app

    - name: Test Service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url

    - name: Post-deployment Pod and Service Check
      run: |
        kubectl get pods -l app=nodejs-app
        kubectl get svc nodejs-app
